language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버 home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r hihiboss-springboot-webservice *
  - mkdir -p deploy
  - mv hihiboss-springboot-webservice.zip deploy/hihiboss-springboot-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: hihiboss-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: hihiboss-springboot-build
    key: hihiboss-springboot-webservice.zip
    bundle_type: zip
    application: hihiboss-springboot-webservice
    deployment_group: hihiboss-springboot-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true